#!/bin/bash

containers_count=$1
containers_str=$(docker ps -a -n $containers_count | egrep -o --regexp="^\S+" | grep -v CONTAINER)
# другой вариант найти первое слово: '^(?:\S+)'

set -f
containers=(${containers_str/\n})

for i in "${!containers[@]}"
do
    echo "Удаляю контейнер ${containers[i]}"
    docker stop  "${containers[i]}"
    docker rm  "${containers[i]}"
done


images_str=$(docker ps -a -n 1 | grep -Po '(?<=^\w{12}\s{3}).+?(?=\s+)')

echo "images: $images_str"

set -f
images=($images_str)
echo "images $images"

for i in "${!images[@]}"
do
    echo "Удаляю image ${images[i]}"
    docker rmi -f "${images[i]}"
done

#echo "$output"
