#! /usr/bin/bash

checkProcesses()
{
    eval string1="$1"
    echo
    echo "List of processes:"
    pgrep -fl ${string1} 
    echo 
}

promptValue() 
{
    read -p "$1"": " answer
}


service="$1"
checkProcesses "\${service}" 

promptValue "R u sure about killing all of this processes? (y/n)"


echo $service

if [ "$answer" == "y" ]; then
    pgrep -fl $service | awk '{print $1}' | xargs kill -9
fi
