#!/usr/bin/bash
AVAILABLE_ARGS=("next", "previous")

DIRECTION=$1

if ! [[ ${AVAILABLE_ARGS[*]} =~ "$DIRECTION" ]]; then
    echo "Wrong arg"
    exit 1
fi

# we are setting up id of every notification to 1
# if notification  with id 1 alreay exist - new norification will replace it
# if not - new notification will appear
NOTIF_ID=1

copyq $DIRECTION
TEXT="$(xclip -sel clipboard -o)"

PID=$(notify-send -t 1000 -r $NOTIF_ID "$TEXT")

